server:
  port: 8080
logging:
  level:
    root: info
    com.cugb.quahog: debug
  file:
    name: log/custom-log.log
spring:
  application:
    name: Quahog
app:
  pull_url: https://resources.ucanfly.com.cn:8081/live/live/2.flv
  model_path: src/main/resources/fire_20250315173627A009.onnx
  push_url: rtmp://202.204.101.80:8082/live/202504?secret=1f146fe5c855d09fdb8e59d203a9fe9e
